  version: '3.8'

  services:
    nginx:
      image: nginx:1.20.1
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
      ports:
        - 8080:80
      container_name: reverse-proxy
      depends_on:
        - bloglist-frontend
        - bloglist-backend

    bloglist-frontend: 
      image: bloglist-frontend
      build:
        context: ./bloglist-frontend/
        dockerfile: Dockerfile
      # volumes:
      #   - ./bloglist-frontend/:/usr/src/app
      environment:
        - REACT_APP_BACKEND_URL=/api
      depends_on:
        - bloglist-backend

    bloglist-backend:
      image: bloglist-backend
      build: 
        context: ./bloglist-backend/
        dockerfile: Dockerfile
      # volumes:
      #   - ./bloglist-backend/:/usr/src/app